export const provinces = [
  { id: "aceh", label: "Aceh" },
  { id: "bali", label: "Bali" },
  { id: "babel", label: "Bangka Belitung" },
  { id: "banten", label: "Banten" },
  { id: "bengkulu", label: "Bengkulu" },
  { id: "diy", label: "DI Yogyakarta" },
  { id: "dki", label: "DKI Jakarta" },
  { id: "gorontalo", label: "Gorontalo" },
  { id: "jambi", label: "Jambi" },
  { id: "jabar", label: "Jawa Barat" },
  { id: "jateng", label: "Jawa Tengah" },
  { id: "jatim", label: "Jawa Timur" },
  { id: "kalbar", label: "Kalimantan Barat" },
  { id: "kalsel", label: "Kalimantan Selatan" },
  { id: "kalteng", label: "Kalimantan Tengah" },
  { id: "kaltim", label: "Kalimantan Timur" },
  { id: "kalut", label: "Kalimantan Utara" },
  { id: "kepri", label: "Kepulauan Riau" },
  { id: "lampung", label: "Lampung" },
  { id: "maluku", label: "Maluku" },
  { id: "malut", label: "Maluku Utara" },
  { id: "ntb", label: "Nusa Tenggara Barat" },
  { id: "ntt", label: "Nusa Tenggara Timur" },
  { id: "papua", label: "Papua" },
  { id: "papuabarat", label: "Papua Barat" },
  { id: "papuabaratdaya", label: "Papua Barat Daya" },
  { id: "papuagunung", label: "Papua Pegunungan" },
  { id: "papuaselatan", label: "Papua Selatan" },
  { id: "papuatengah", label: "Papua Tengah" },
  { id: "papuadaya", label: "Papua Barat Daya" },
  { id: "riau", label: "Riau" },
  { id: "sulbar", label: "Sulawesi Barat" },
  { id: "sulsel", label: "Sulawesi Selatan" },
  { id: "sulteng", label: "Sulawesi Tengah" },
  { id: "sultra", label: "Sulawesi Tenggara" },
  { id: "sulut", label: "Sulawesi Utara" },
  { id: "sumbar", label: "Sumatera Barat" },
  { id: "sumsel", label: "Sumatera Selatan" },
  { id: "sumut", label: "Sumatera Utara" },
];

export const citiesByProvince = {
  aceh: [
    { id: "banda-aceh", label: "Banda Aceh" },
    { id: "sabang", label: "Sabang" },
    { id: "langsa", label: "Langsa" },
    { id: "lhokseumawe", label: "Lhokseumawe" },
    { id: "subulussalam", label: "Subulussalam" },

    { id: "aceh-barat", label: "Aceh Barat" },
    { id: "aceh-barat-daya", label: "Aceh Barat Daya" },
    { id: "aceh-besar", label: "Aceh Besar" },
    { id: "aceh-selatan", label: "Aceh Selatan" },
    { id: "aceh-singkil", label: "Aceh Singkil" },
    { id: "aceh-tamiang", label: "Aceh Tamiang" },
    { id: "aceh-tengah", label: "Aceh Tengah" },
    { id: "aceh-tenggara", label: "Aceh Tenggara" },
    { id: "aceh-timur", label: "Aceh Timur" },
    { id: "aceh-utara", label: "Aceh Utara" },

    { id: "bener-meriah", label: "Bener Meriah" },
    { id: "bireuen", label: "Bireuen" },
    { id: "gayo-lues", label: "Gayo Lues" },
    { id: "nagan-raya", label: "Nagan Raya" },
    { id: "pidie", label: "Pidie" },
    { id: "pidie-jaya", label: "Pidie Jaya" },
    { id: "simeulue", label: "Simeulue" },
  ],

  bali: [
    { id: "denpasar", label: "Denpasar" },

    { id: "badung", label: "Badung" },
    { id: "bangli", label: "Bangli" },
    { id: "buleleng", label: "Buleleng" },
    { id: "gianyar", label: "Gianyar" },
    { id: "jembrana", label: "Jembrana" },
    { id: "karangasem", label: "Karangasem" },
    { id: "klungkung", label: "Klungkung" },
    { id: "tabanan", label: "Tabanan" },
  ],

  babel: [
    { id: "pangkalpinang", label: "Pangkalpinang" },

    { id: "bangka", label: "Bangka" },
    { id: "bangka-barat", label: "Bangka Barat" },
    { id: "bangka-selatan", label: "Bangka Selatan" },
    { id: "bangka-tengah", label: "Bangka Tengah" },
    { id: "belitung", label: "Belitung" },
    { id: "belitung-timur", label: "Belitung Timur" },
  ],

  banten: [
    { id: "cilegon", label: "Cilegon" },
    { id: "serang-kota", label: "Serang" },
    { id: "tangerang-kota", label: "Tangerang" },
    { id: "tangerang-selatan", label: "Tangerang Selatan" },

    { id: "lebak", label: "Lebak" },
    { id: "pandeglang", label: "Pandeglang" },
    { id: "serang-kabupaten", label: "Serang" },
    { id: "tangerang-kabupaten", label: "Tangerang" },
  ],

  bengkulu: [
    { id: "bengkulu-kota", label: "Bengkulu" },

    { id: "bengkulu-selatan", label: "Bengkulu Selatan" },
    { id: "bengkulu-tengah", label: "Bengkulu Tengah" },
    { id: "bengkulu-utara", label: "Bengkulu Utara" },
    { id: "kaur", label: "Kaur" },
    { id: "kepahiang", label: "Kepahiang" },
    { id: "lebong", label: "Lebong" },
    { id: "mukomuko", label: "Mukomuko" },
    { id: "rejang-lebong", label: "Rejang Lebong" },
    { id: "seluma", label: "Seluma" },
  ],

  diy: [
    { id: "yogyakarta", label: "Yogyakarta" },

    { id: "bantul", label: "Bantul" },
    { id: "sleman", label: "Sleman" },
    { id: "gunungkidul", label: "Gunungkidul" },
    { id: "kulon-progo", label: "Kulon Progo" },
  ],

  dki: [
    { id: "jakarta-pusat", label: "Jakarta Pusat" },
    { id: "jakarta-utara", label: "Jakarta Utara" },
    { id: "jakarta-barat", label: "Jakarta Barat" },
    { id: "jakarta-selatan", label: "Jakarta Selatan" },
    { id: "jakarta-timur", label: "Jakarta Timur" },

    { id: "kepulauan-seribu", label: "Kepulauan Seribu" },
  ],

  gorontalo: [
    { id: "gorontalo-kota", label: "Kota Gorontalo" },

    { id: "boalemo", label: "Boalemo" },
    { id: "bone-bolango", label: "Bone Bolango" },
    { id: "gorontalo-kabupaten", label: "Gorontalo" },
    { id: "gorontalo-utara", label: "Gorontalo Utara" },
    { id: "pohuwato", label: "Pohuwato" },
  ],

  jambi: [
    { id: "jambi-kota", label: "Jambi" },

    { id: "batanghari", label: "Batanghari" },
    { id: "bungo", label: "Bungo" },
    { id: "kerinci", label: "Kerinci" },
    { id: "merangin", label: "Merangin" },
    { id: "muaro-jambi", label: "Muaro Jambi" },
    { id: "sarolangun", label: "Sarolangun" },
    { id: "tanjung-jabung-barat", label: "Tanjung Jabung Barat" },
    { id: "tanjung-jabung-timur", label: "Tanjung Jabung Timur" },
    { id: "tebo", label: "Tebo" },
  ],

  jabar: [
    { id: "bandung-kota", label: "Bandung" },
    { id: "banjar", label: "Banjar" },
    { id: "bekasi-kota", label: "Bekasi" },
    { id: "bogor-kota", label: "Bogor" },
    { id: "cimahi", label: "Cimahi" },
    { id: "cirebon-kota", label: "Cirebon" },
    { id: "depok", label: "Depok" },
    { id: "sukabumi-kota", label: "Sukabumi" },

    { id: "bandung", label: "Bandung (Kabupaten)" },
    { id: "bandung-barat", label: "Bandung Barat" },
    { id: "bekasi", label: "Bekasi (Kabupaten)" },
    { id: "bogor", label: "Bogor (Kabupaten)" },
    { id: "ciamis", label: "Ciamis" },
    { id: "cianjur", label: "Cianjur" },
    { id: "cirebon", label: "Cirebon (Kabupaten)" },
    { id: "garut", label: "Garut" },
    { id: "indramayu", label: "Indramayu" },
    { id: "karawang", label: "Karawang" },
    { id: "kuningan", label: "Kuningan" },
    { id: "majalengka", label: "Majalengka" },
    { id: "pangandaran", label: "Pangandaran" },
    { id: "purwakarta", label: "Purwakarta" },
    { id: "subang", label: "Subang" },
    { id: "sukabumi", label: "Sukabumi (Kabupaten)" },
    { id: "sumedang", label: "Sumedang" },
    { id: "tasikmalaya-kota", label: "Tasikmalaya" },
    { id: "tasikmalaya", label: "Tasikmalaya (Kabupaten)" },
  ],

  jateng: [
    { id: "semarang-kota", label: "Semarang" },
    { id: "solo", label: "Surakarta" },
    { id: "magelang-kota", label: "Magelang" },
    { id: "pekalongan-kota", label: "Pekalongan" },
    { id: "salatiga", label: "Salatiga" },
    { id: "tegal-kota", label: "Tegal" },

    { id: "banjarnegara", label: "Banjarnegara" },
    { id: "banyumas", label: "Banyumas" },
    { id: "batang", label: "Batang" },
    { id: "blora", label: "Blora" },
    { id: "boyolali", label: "Boyolali" },
    { id: "brebes", label: "Brebes" },
    { id: "cilacap", label: "Cilacap" },
    { id: "demak", label: "Demak" },
    { id: "grobogan", label: "Grobogan" },
    { id: "jepara", label: "Jepara" },
    { id: "karanganyar", label: "Karanganyar" },
    { id: "kendal", label: "Kendal" },
    { id: "klaten", label: "Klaten" },
    { id: "kudus", label: "Kudus" },
    { id: "magelang", label: "Magelang (Kabupaten)" },
    { id: "pati", label: "Pati" },
    { id: "pekalongan", label: "Pekalongan (Kabupaten)" },
    { id: "pemalang", label: "Pemalang" },
    { id: "purbalingga", label: "Purbalingga" },
    { id: "purworejo", label: "Purworejo" },
    { id: "rembang", label: "Rembang" },
    { id: "semarang", label: "Semarang (Kabupaten)" },
    { id: "sragen", label: "Sragen" },
    { id: "sukoharjo", label: "Sukoharjo" },
    { id: "tegal", label: "Tegal (Kabupaten)" },
    { id: "temanggung", label: "Temanggung" },
    { id: "wonogiri", label: "Wonogiri" },
    { id: "wonosobo", label: "Wonosobo" },
  ],

  jatim: [
    { id: "surabaya", label: "Surabaya" },
    { id: "malang-kota", label: "Malang" },
    { id: "kediri-kota", label: "Kediri" },
    { id: "blitar-kota", label: "Blitar" },
    { id: "madiun-kota", label: "Madiun" },
    { id: "probolinggo-kota", label: "Probolinggo" },
    { id: "pasuruan-kota", label: "Pasuruan" },

    { id: "bangkalan", label: "Bangkalan" },
    { id: "banyuwangi", label: "Banyuwangi" },
    { id: "blitar", label: "Blitar (Kabupaten)" },
    { id: "bojonegoro", label: "Bojonegoro" },
    { id: "bondowoso", label: "Bondowoso" },
    { id: "gresik", label: "Gresik" },
    { id: "jember", label: "Jember" },
    { id: "jombang", label: "Jombang" },
    { id: "kediri", label: "Kediri (Kabupaten)" },
    { id: "lamongan", label: "Lamongan" },
    { id: "lumajang", label: "Lumajang" },
    { id: "madiun", label: "Madiun (Kabupaten)" },
    { id: "magetan", label: "Magetan" },
    { id: "malang", label: "Malang (Kabupaten)" },
    { id: "mojokerto", label: "Mojokerto (Kabupaten)" },
    { id: "nganjuk", label: "Nganjuk" },
    { id: "ngawi", label: "Ngawi" },
    { id: "pacitan", label: "Pacitan" },
    { id: "pamekasan", label: "Pamekasan" },
    { id: "pasuruan", label: "Pasuruan (Kabupaten)" },
    { id: "ponorogo", label: "Ponorogo" },
    { id: "probolinggo", label: "Probolinggo (Kabupaten)" },
    { id: "sampang", label: "Sampang" },
    { id: "sidoarjo", label: "Sidoarjo" },
    { id: "situbondo", label: "Situbondo" },
    { id: "sumenep", label: "Sumenep" },
    { id: "trenggalek", label: "Trenggalek" },
    { id: "tuban", label: "Tuban" },
    { id: "tulungagung", label: "Tulungagung" },
  ],

  kalbar: [
    { id: "pontianak-kota", label: "Pontianak" },
    { id: "singkawang", label: "Singkawang" },

    { id: "bengkayang", label: "Bengkayang" },
    { id: "kapuas-hulu", label: "Kapuas Hulu" },
    { id: "kayong-utara", label: "Kayong Utara" },
    { id: "ketapang", label: "Ketapang" },
    { id: "kubu-raya", label: "Kubu Raya" },
    { id: "landak", label: "Landak" },
    { id: "melawi", label: "Melawi" },
    { id: "mempawah", label: "Mempawah" },
    { id: "sambas", label: "Sambas" },
    { id: "sanggau", label: "Sanggau" },
    { id: "sekadau", label: "Sekadau" },
    { id: "sintang", label: "Sintang" },
  ],

  kalsel: [
    { id: "banjarmasin", label: "Banjarmasin" },
    { id: "banjarbaru", label: "Banjarbaru" },

    { id: "balangan", label: "Balangan" },
    { id: "banjar", label: "Banjar" },
    { id: "barito-kuala", label: "Barito Kuala" },
    { id: "hulu-sungai-selatan", label: "Hulu Sungai Selatan" },
    { id: "hulu-sungai-tengah", label: "Hulu Sungai Tengah" },
    { id: "hulu-sungai-utara", label: "Hulu Sungai Utara" },
    { id: "kotabaru", label: "Kotabaru" },
    { id: "tabalong", label: "Tabalong" },
    { id: "tanah-bumbu", label: "Tanah Bumbu" },
    { id: "tanah-laut", label: "Tanah Laut" },
    { id: "tapin", label: "Tapin" },
  ],

  kalteng: [
    { id: "palangka-raya", label: "Palangka Raya" },

    { id: "barito-selatan", label: "Barito Selatan" },
    { id: "barito-timur", label: "Barito Timur" },
    { id: "barito-utara", label: "Barito Utara" },
    { id: "gunung-mas", label: "Gunung Mas" },
    { id: "kapuas", label: "Kapuas" },
    { id: "katingan", label: "Katingan" },
    { id: "kotawaringin-barat", label: "Kotawaringin Barat" },
    { id: "kotawaringin-timur", label: "Kotawaringin Timur" },
    { id: "lamandau", label: "Lamandau" },
    { id: "murung-raya", label: "Murung Raya" },
    { id: "pulang-pisau", label: "Pulang Pisau" },
    { id: "sukamara", label: "Sukamara" },
  ],

  kaltim: [
    { id: "balikpapan", label: "Balikpapan" },
    { id: "bontang", label: "Bontang" },
    { id: "samarinda", label: "Samarinda" },

    { id: "berau", label: "Berau" },
    { id: "kutai-barat", label: "Kutai Barat" },
    { id: "kutai-kartanegara", label: "Kutai Kartanegara" },
    { id: "kutai-timur", label: "Kutai Timur" },
    { id: "mahakam-ulu", label: "Mahakam Ulu" },
    { id: "paser", label: "Paser" },
  ],

  kalut: [
    { id: "tarakan", label: "Tarakan" },

    { id: "bulungan", label: "Bulungan" },
    { id: "malinau", label: "Malinau" },
    { id: "nunukan", label: "Nunukan" },
    { id: "tana-tidung", label: "Tana Tidung" },
  ],

  kepri: [
    { id: "batam", label: "Batam" },
    { id: "tanjungpinang", label: "Tanjung Pinang" },

    { id: "bintan", label: "Bintan" },
    { id: "karimun", label: "Karimun" },
    { id: "kepulauan-anambas", label: "Kepulauan Anambas" },
    { id: "lingga", label: "Lingga" },
    { id: "natuna", label: "Natuna" },
  ],

  lampung: [
    { id: "bandar-lampung", label: "Bandar Lampung" },
    { id: "metro", label: "Metro" },

    { id: "lampung-barat", label: "Lampung Barat" },
    { id: "lampung-selatan", label: "Lampung Selatan" },
    { id: "lampung-tengah", label: "Lampung Tengah" },
    { id: "lampung-utara", label: "Lampung Utara" },
    { id: "mesuji", label: "Mesuji" },
    { id: "pesawaran", label: "Pesawaran" },
    { id: "pesisir-barat", label: "Pesisir Barat" },
    { id: "pringsewu", label: "Pringsewu" },
    { id: "tanggamus", label: "Tanggamus" },
    { id: "tulang-bawang", label: "Tulang Bawang" },
    { id: "tulang-bawang-barat", label: "Tulang Bawang Barat" },
    { id: "way-kanan", label: "Way Kanan" },
  ],

  maluku: [
    { id: "ambon", label: "Ambon" },
    { id: "tual", label: "Tual" },

    { id: "buru", label: "Buru" },
    { id: "buru-selatan", label: "Buru Selatan" },
    { id: "kepulauan-aru", label: "Kepulauan Aru" },
    { id: "maluku-barat-daya", label: "Maluku Barat Daya" },
    { id: "maluku-tengah", label: "Maluku Tengah" },
    { id: "maluku-tenggara", label: "Maluku Tenggara" },
    { id: "seram-bagian-barat", label: "Seram Bagian Barat" },
    { id: "seram-bagian-timur", label: "Seram Bagian Timur" },
    { id: "kepulauan-tanimbar", label: "Kepulauan Tanimbar" },
  ],

  malut: [
    { id: "tidore-kepulauan", label: "Tidore Kepulauan" },
    { id: "ternate", label: "Ternate" },

    { id: "halmahera-barat", label: "Halmahera Barat" },
    { id: "halmahera-tengah", label: "Halmahera Tengah" },
    { id: "halmahera-utara", label: "Halmahera Utara" },
    { id: "halmahera-selatan", label: "Halmahera Selatan" },
    { id: "halmahera-timur", label: "Halmahera Timur" },
    { id: "kepulauan-sula", label: "Kepulauan Sula" },
    { id: "pulau-morotai", label: "Pulau Morotai" },
    { id: "pulau-taliabu", label: "Pulau Taliabu" },
  ],

  ntb: [
    { id: "mataram", label: "Mataram" },
    { id: "bima-kota", label: "Bima" },

    { id: "bima", label: "Bima (Kabupaten)" },
    { id: "dompu", label: "Dompu" },
    { id: "lombok-barat", label: "Lombok Barat" },
    { id: "lombok-tengah", label: "Lombok Tengah" },
    { id: "lombok-timur", label: "Lombok Timur" },
    { id: "lombok-utara", label: "Lombok Utara" },
    { id: "sumbawa", label: "Sumbawa" },
    { id: "sumbawa-barat", label: "Sumbawa Barat" },
  ],

  ntt: [
    { id: "kupang", label: "Kupang" },

    { id: "alor", label: "Alor" },
    { id: "belu", label: "Belu" },
    { id: "ende", label: "Ende" },
    { id: "flores-timur", label: "Flores Timur" },
    { id: "kupang-kabupaten", label: "Kupang (Kabupaten)" },
    { id: "lembata", label: "Lembata" },
    { id: "malaka", label: "Malaka" },
    { id: "manggarai", label: "Manggarai" },
    { id: "manggarai-barat", label: "Manggarai Barat" },
    { id: "manggarai-timur", label: "Manggarai Timur" },
    { id: "nagekeo", label: "Nagekeo" },
    { id: "ngada", label: "Ngada" },
    { id: "rote-ndao", label: "Rote Ndao" },
    { id: "sabu-raijua", label: "Sabu Raijua" },
    { id: "sikka", label: "Sikka" },
    { id: "sumba-barat", label: "Sumba Barat" },
    { id: "sumba-barat-daya", label: "Sumba Barat Daya" },
    { id: "sumba-tengah", label: "Sumba Tengah" },
    { id: "sumba-timur", label: "Sumba Timur" },
    { id: "timor-tengah-selatan", label: "Timor Tengah Selatan" },
    { id: "timor-tengah-utara", label: "Timor Tengah Utara" },
  ],

  papua: [
    { id: "jayapura-kota", label: "Jayapura" },

    { id: "biak-numfor", label: "Biak Numfor" },
    { id: "jayapura-kabupaten", label: "Jayapura (Kabupaten)" },
    { id: "keerom", label: "Keerom" },
    { id: "kepulauan-yapen", label: "Kepulauan Yapen" },
    { id: "mamberamo-raya", label: "Mamberamo Raya" },
    { id: "sarmi", label: "Sarmi" },
    { id: "supiori", label: "Supiori" },
    { id: "waropen", label: "Waropen" },
    { id: "intan-jaya", label: "Intan Jaya" },
    { id: "mimika", label: "Mimika" },
    { id: "nabire", label: "Nabire" },
    { id: "paniai", label: "Paniai" },
    { id: "pegunungan-bintang", label: "Pegunungan Bintang" },
    { id: "puncak", label: "Puncak" },
    { id: "puncak-jaya", label: "Puncak Jaya" },
    { id: "dogiyai", label: "Dogiyai" },
    { id: "deiyai", label: "Deiyai" },
    { id: "yahukimo", label: "Yahukimo" },
    { id: "yalimo", label: "Yalimo" },
  ],

  papuabarat: [
    { id: "manokwari", label: "Manokwari" },
    { id: "sorong-kota", label: "Sorong" },

    { id: "fakfak", label: "Fakfak" },
    { id: "kaimana", label: "Kaimana" },
    { id: "manokwari-selatan", label: "Manokwari Selatan" },
    { id: "maybrat", label: "Maybrat" },
    { id: "raja-ampat", label: "Raja Ampat" },
    { id: "sorong", label: "Sorong (Kabupaten)" },
    { id: "sorong-selatan", label: "Sorong Selatan" },
    { id: "tambrauw", label: "Tambrauw" },
    { id: "teluk-bintuni", label: "Teluk Bintuni" },
    { id: "teluk-wondama", label: "Teluk Wondama" },
  ],

  papuabaratdaya: [
    { id: "sorong-kota", label: "Sorong" },

    { id: "raja-ampat", label: "Raja Ampat" },
    { id: "sorong", label: "Sorong (Kabupaten)" },
    { id: "sorong-selatan", label: "Sorong Selatan" },
    { id: "tambrauw", label: "Tambrauw" },
    { id: "maybrat", label: "Maybrat" },
  ],

  papuagunung: [
    { id: "jayawijaya", label: "Jayawijaya" },

    { id: "lanny-jaya", label: "Lanny Jaya" },
    { id: "mamberamo-tengah", label: "Mamberamo Tengah" },
    { id: "nduga", label: "Nduga" },
    { id: "pegonungan-bintang", label: "Pegunungan Bintang" },
    { id: "tolikara", label: "Tolikara" },
    { id: "yahukimo", label: "Yahukimo" },
    { id: "yalimo", label: "Yalimo" },
  ],

  papuaselatan: [
    { id: "merauke", label: "Merauke" },

    { id: "asmat", label: "Asmat" },
    { id: "boven-digoel", label: "Boven Digoel" },
    { id: "mappi", label: "Mappi" },
  ],

  papuatengah: [
    { id: "nabire", label: "Nabire" },

    { id: "deiyai", label: "Deiyai" },
    { id: "dogiyai", label: "Dogiyai" },
    { id: "intan-jaya", label: "Intan Jaya" },
    { id: "mimika", label: "Mimika" },
    { id: "paniai", label: "Paniai" },
    { id: "puncak", label: "Puncak" },
    { id: "puncak-jaya", label: "Puncak Jaya" },
  ],

  papuadaya: [
    { id: "sorong-kota", label: "Sorong" },

    { id: "raja-ampat", label: "Raja Ampat" },
    { id: "sorong", label: "Sorong (Kabupaten)" },
    { id: "sorong-selatan", label: "Sorong Selatan" },
    { id: "tambrauw", label: "Tambrauw" },
    { id: "maybrat", label: "Maybrat" },
  ],

  riau: [
    { id: "pekanbaru", label: "Pekanbaru" },

    { id: "bengkalis", label: "Bengkalis" },
    { id: "indragiri-hilir", label: "Indragiri Hilir" },
    { id: "indragiri-hulu", label: "Indragiri Hulu" },
    { id: "kampar", label: "Kampar" },
    { id: "kepulauan-meranti", label: "Kepulauan Meranti" },
    { id: "kuantan-singingi", label: "Kuantan Singingi" },
    { id: "pelalawan", label: "Pelalawan" },
    { id: "rokan-hilir", label: "Rokan Hilir" },
    { id: "rokan-hulu", label: "Rokan Hulu" },
    { id: "siak", label: "Siak" },
  ],

  sulbar: [
    { id: "mamuju", label: "Mamuju" },
    { id: "polewali-mandar", label: "Polewali Mandar" },

    { id: "majene", label: "Majene" },
    { id: "mamuju-tengah", label: "Mamuju Tengah" },
    { id: "mamuju-utara", label: "Mamuju Utara" },
    { id: "pasangkayu", label: "Pasangkayu" },
  ],

  sulsel: [
    { id: "makassar", label: "Makassar" },
    { id: "palopo", label: "Palopo" },
    { id: "parepare", label: "Parepare" },

    { id: "bantaeng", label: "Bantaeng" },
    { id: "barru", label: "Barru" },
    { id: "bone", label: "Bone" },
    { id: "bulukumba", label: "Bulukumba" },
    { id: "enrekang", label: "Enrekang" },
    { id: "gowa", label: "Gowa" },
    { id: "jeneponto", label: "Jeneponto" },
    { id: "kepulauan-selayar", label: "Kepulauan Selayar" },
    { id: "luwu", label: "Luwu" },
    { id: "luwu-timur", label: "Luwu Timur" },
    { id: "luwu-utara", label: "Luwu Utara" },
    { id: "maros", label: "Maros" },
    { id: "pangkajene-kepulauan", label: "Pangkajene dan Kepulauan" },
    { id: "pinrang", label: "Pinrang" },
    { id: "sidenreng-rappang", label: "Sidenreng Rappang" },
    { id: "sinjai", label: "Sinjai" },
    { id: "soppeng", label: "Soppeng" },
    { id: "takalar", label: "Takalar" },
    { id: "tana-toraja", label: "Tana Toraja" },
    { id: "toraja-utara", label: "Toraja Utara" },
    { id: "wajo", label: "Wajo" },
  ],

  sulteng: [
    { id: "palu", label: "Palu" },

    { id: "banggai", label: "Banggai" },
    { id: "banggai-kepulauan", label: "Banggai Kepulauan" },
    { id: "banggai-laut", label: "Banggai Laut" },
    { id: "buol", label: "Buol" },
    { id: "donggala", label: "Donggala" },
    { id: "morowali", label: "Morowali" },
    { id: "morowali-utara", label: "Morowali Utara" },
    { id: "parigi-moutong", label: "Parigi Moutong" },
    { id: "poso", label: "Poso" },
    { id: "sigi", label: "Sigi" },
    { id: "tojo-una-una", label: "Tojo Una-Una" },
    { id: "toli-toli", label: "Toli-Toli" },
  ],

  sultra: [
    { id: "kendari", label: "Kendari" },
    { id: "bau-bau", label: "Baubau" },

    { id: "bombana", label: "Bombana" },
    { id: "buton", label: "Buton" },
    { id: "buton-selatan", label: "Buton Selatan" },
    { id: "buton-tengah", label: "Buton Tengah" },
    { id: "buton-utara", label: "Buton Utara" },
    { id: "kolaka", label: "Kolaka" },
    { id: "kolaka-timur", label: "Kolaka Timur" },
    { id: "kolaka-utara", label: "Kolaka Utara" },
    { id: "konawe", label: "Konawe" },
    { id: "konawe-kepulauan", label: "Konawe Kepulauan" },
    { id: "konawe-selatan", label: "Konawe Selatan" },
    { id: "konawe-utara", label: "Konawe Utara" },
    { id: "muna", label: "Muna" },
    { id: "muna-barat", label: "Muna Barat" },
    { id: "wakatobi", label: "Wakatobi" },
  ],

  sulut: [
    { id: "manado", label: "Manado" },
    { id: "bitung", label: "Bitung" },
    { id: "tomohon", label: "Tomohon" },
    { id: "kotamobagu", label: "Kotamobagu" },

    { id: "bolaang-mongondow", label: "Bolaang Mongondow" },
    { id: "bolaang-mongondow-selatan", label: "Bolaang Mongondow Selatan" },
    { id: "bolaang-mongondow-timur", label: "Bolaang Mongondow Timur" },
    { id: "bolaang-mongondow-utara", label: "Bolaang Mongondow Utara" },
    { id: "minahasa", label: "Minahasa" },
    { id: "minahasa-selatan", label: "Minahasa Selatan" },
    { id: "minahasa-tenggara", label: "Minahasa Tenggara" },
    { id: "minahasa-utara", label: "Minahasa Utara" },
    { id: "kepulauan-sangihe", label: "Kepulauan Sangihe" },
    {
      id: "kepulauan-siau-tagulandang-biaro",
      label: "Kepulauan Siau Tagulandang Biaro",
    },
    { id: "kepulauan-talaud", label: "Kepulauan Talaud" },
  ],

  sumbar: [
    { id: "padang", label: "Padang" },
    { id: "bukittinggi", label: "Bukittinggi" },
    { id: "padang-panjang", label: "Padang Panjang" },
    { id: "pariaman", label: "Pariaman" },
    { id: "payakumbuh", label: "Payakumbuh" },
    { id: "sawahlunto", label: "Sawahlunto" },

    { id: "agam", label: "Agam" },
    { id: "dharmasraya", label: "Dharmasraya" },
    { id: "kepulauan-mentawai", label: "Kepulauan Mentawai" },
    { id: "lima-puluh-kota", label: "Lima Puluh Kota" },
    { id: "padang-pariaman", label: "Padang Pariaman" },
    { id: "pasaman", label: "Pasaman" },
    { id: "pasaman-barat", label: "Pasaman Barat" },
    { id: "pesisir-selatan", label: "Pesisir Selatan" },
    { id: "sijunjung", label: "Sijunjung" },
    { id: "solok", label: "Solok" },
    { id: "solok-selatan", label: "Solok Selatan" },
    { id: "tanah-datar", label: "Tanah Datar" },
  ],

  sumsel: [
    { id: "palembang", label: "Palembang" },
    { id: "lubuk-linggau", label: "Lubuk Linggau" },
    { id: "pagar-alam", label: "Pagar Alam" },
    { id: "prabumulih", label: "Prabumulih" },

    { id: "banyuasin", label: "Banyuasin" },
    { id: "empat-lawang", label: "Empat Lawang" },
    { id: "lahat", label: "Lahat" },
    { id: "muara-enim", label: "Muara Enim" },
    { id: "musi-banyuasin", label: "Musi Banyuasin" },
    { id: "musi-rawas", label: "Musi Rawas" },
    { id: "musi-rawas-utara", label: "Musi Rawas Utara" },
    { id: "ogan-ilir", label: "Ogan Ilir" },
    { id: "ogan-komering-ilir", label: "Ogan Komering Ilir" },
    { id: "ogan-komering-ulu", label: "Ogan Komering Ulu" },
    { id: "ogan-komering-ulu-selatan", label: "Ogan Komering Ulu Selatan" },
    { id: "ogan-komering-ulu-timur", label: "Ogan Komering Ulu Timur" },
    { id: "penukal-abab-lematang-ilir", label: "Penukal Abab Lematang Ilir" },
    { id: "oku-timur", label: "OKU Timur" },
  ],

  sumut: [
    { id: "medan", label: "Medan" },
    { id: "binjai", label: "Binjai" },
    { id: "padang-sidempuan", label: "Padang Sidempuan" },
    { id: "pematang-siantar", label: "Pematang Siantar" },
    { id: "sibolga", label: "Sibolga" },
    { id: "tanjungbalai", label: "Tanjung Balai" },
    { id: "tebing-tinggi", label: "Tebing Tinggi" },

    { id: "asahan", label: "Asahan" },
    { id: "batu-bara", label: "Batu Bara" },
    { id: "dairi", label: "Dairi" },
    { id: "deli-serdang", label: "Deli Serdang" },
    { id: "humbang-hasundutan", label: "Humbang Hasundutan" },
    { id: "karo", label: "Karo" },
    { id: "labuhanbatu", label: "Labuhanbatu" },
    { id: "labuhanbatu-selatan", label: "Labuhanbatu Selatan" },
    { id: "labuhanbatu-utara", label: "Labuhanbatu Utara" },
    { id: "langkat", label: "Langkat" },
    { id: "mandailing-natal", label: "Mandailing Natal" },
    { id: "nias", label: "Nias" },
    { id: "nias-barat", label: "Nias Barat" },
    { id: "nias-selatan", label: "Nias Selatan" },
    { id: "nias-utara", label: "Nias Utara" },
    { id: "padang-lawas", label: "Padang Lawas" },
    { id: "padang-lawas-utara", label: "Padang Lawas Utara" },
    { id: "pakpak-bharat", label: "Pakpak Bharat" },
    { id: "samosir", label: "Samosir" },
    { id: "serdang-bedagai", label: "Serdang Bedagai" },
    { id: "simalungun", label: "Simalungun" },
    { id: "tapanuli-selatan", label: "Tapanuli Selatan" },
    { id: "tapanuli-tengah", label: "Tapanuli Tengah" },
    { id: "tapanuli-utara", label: "Tapanuli Utara" },
    { id: "toba", label: "Toba" },
  ],
};
